name: Create Tag and Release
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref (tag) to build'
        required: true
        default: '0.1.0'
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ vars.REGISTRY_SERVER != '' && vars.REGISTRY_USERNAME != '' }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5
      - name: 'Create tag'
        uses: actions/github-script@v5
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.event.inputs.ref }}',
              sha: context.sha
            })
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        with:
          tag_name: '${{ github.event.inputs.ref }}'
          release_name: 'Release ${{ github.event.inputs.ref }}'
          draft: false
          prerelease: false
